import type { CourseModule } from './types';

/** Slides: `slidesManifest` → `public/e-courses/modules/{id}/slides/`. Sync: `npm run sync-module1-slides` … `sync-module7-slides` (see scripts; env MODULEn_SLIDES_DIR). */
export const COURSE_MODULES: CourseModule[] = [
  {
    id: 'ms-really',
    number: 1,
    title: 'What is a Management System (Really?)',
    tagline: 'Understand how work is structured and controlled.',
    outcomes: [
      'Tell the difference between random activity and a real system',
      'Name the basic parts: inputs, process, outputs, and feedback',
      'Spot where work is informal versus where it is defined',
      'Connect everyday tasks to how leadership sets direction',
    ],
    estimatedMinutes: 35,
    skillLevel: 'Beginner',
    slidesManifest: '/e-courses/modules/ms-really/slides/manifest.json',
  },
  {
    id: 'quality-iso-simplified',
    number: 2,
    title: 'Understanding Quality (ISO 9001 Simplified)',
    tagline: 'Learn what quality really means in business.',
    outcomes: [
      'Use a simple definition of quality: meeting needs, every time',
      'See how customer focus shows up in real decisions',
      'Relate leadership and engagement to consistent results',
      'Know what auditors look for without drowning in jargon',
    ],
    estimatedMinutes: 40,
    skillLevel: 'Beginner',
    slidesManifest: '/e-courses/modules/quality-iso-simplified/slides/manifest.json',
  },
  {
    id: 'process-thinking',
    number: 3,
    title: 'Process Thinking (The Backbone of QMS)',
    tagline: 'See how work flows from input to output.',
    outcomes: [
      'Draw a one-page map of a process you actually run',
      'Identify handoffs where mistakes or delays usually appear',
      'Set clear ownership for each step',
      'Choose one metric that proves the process is under control',
    ],
    estimatedMinutes: 45,
    skillLevel: 'Beginner',
    slidesManifest: '/e-courses/modules/process-thinking/slides/manifest.json',
  },
  {
    id: 'risk-based-thinking',
    number: 4,
    title: 'Risk-Based Thinking (Prevent Problems Early)',
    tagline: 'Identify and reduce risks before they occur.',
    outcomes: [
      'Separate risks from issues after the fact',
      'Use a light template: likelihood, impact, and controls',
      'Prioritize what to fix first with your team',
      'Link risk actions to who does what and by when',
    ],
    estimatedMinutes: 40,
    skillLevel: 'Intermediate',
    slidesManifest: '/e-courses/modules/risk-based-thinking/slides/manifest.json',
  },
  {
    id: 'documentation-works',
    number: 5,
    title: 'Documentation That Works (Not Paperwork)',
    tagline: 'Create simple, useful systems people actually follow.',
    outcomes: [
      'Decide what must be written versus what can stay verbal',
      'Write short procedures people can use on day one',
      'Keep version control practical, not bureaucratic',
      'Align records to evidence you would show in an audit',
    ],
    estimatedMinutes: 50,
    skillLevel: 'Intermediate',
    slidesManifest: '/e-courses/modules/documentation-works/slides/manifest.json',
  },
  {
    id: 'people-drive-quality',
    number: 6,
    title: 'People Drive Quality (Execution Reality)',
    tagline: 'Understand behavior, culture, and accountability.',
    outcomes: [
      'Set expectations that match how the job is really done',
      'Use competence and training where it moves the needle',
      'Make accountability visible without blame theatre',
      'Spot culture signals that help or hurt consistency',
    ],
    estimatedMinutes: 42,
    skillLevel: 'Intermediate',
    slidesManifest: '/e-courses/modules/people-drive-quality/slides/manifest.json',
  },
  {
    id: 'monitoring-measurement',
    number: 7,
    title: 'Monitoring, Measurement & Data',
    tagline: 'Use data to see truth and drive decisions.',
    outcomes: [
      'Pick a small set of KPIs tied to customer and process health',
      'Collect data in a way frontline teams will sustain',
      'Turn charts into decisions, not slide filler',
      'Know when to act versus when to watch a trend longer',
    ],
    estimatedMinutes: 48,
    skillLevel: 'Intermediate',
    slidesManifest: '/e-courses/modules/monitoring-measurement/slides/manifest.json',
  },
  {
    id: 'audits-capa',
    number: 8,
    title: 'Audits & Corrective Action (CAPA)',
    tagline: 'Fix problems properly and prevent recurrence.',
    outcomes: [
      'Run an internal audit conversation that builds trust',
      'Write corrective actions that fix root cause, not symptoms',
      'Close the loop with verification and follow-up',
      'Use CAPA data to improve the system, not hide mistakes',
    ],
    estimatedMinutes: 55,
    skillLevel: 'Intermediate',
    comingSoon: true,
  },
  {
    id: 'continual-improvement',
    number: 9,
    title: 'Continual Improvement & Business Performance',
    tagline: 'Turn quality into growth and long-term success.',
    outcomes: [
      'Run management review as a working meeting, not a ritual',
      'Prioritize improvements that customers and margins feel',
      'Build a simple pipeline from idea to implemented change',
      'Connect QMS maturity to revenue, cost, and reputation',
    ],
    estimatedMinutes: 50,
    skillLevel: 'Intermediate',
    comingSoon: true,
  },
];
