/* eslint-disable */
// Generated by scripts/generate-module-quiz-bank.mjs — do not edit by hand.

export type QuizChoiceKey = 'A' | 'B' | 'C' | 'D';

export type QuizQuestion = {
  id: number;
  question: string;
  choices: { key: QuizChoiceKey; text: string }[];
  correct: QuizChoiceKey;
  /** Rationale from the quiz document answer key (may be empty if not present). */
  explanation: string;
};

export const MODULE_QUIZ_BANK: Record<string, QuizQuestion[]> = {
  "ms-really": [
    {
      "id": 1,
      "question": "What is the fundamental difference between \"Random Work\" and \"Systematic Work\"?",
      "choices": [
        {
          "key": "A",
          "text": "Random work is faster, while systematic work is slower."
        },
        {
          "key": "B",
          "text": "Systematic work relies entirely on employee mood and urgency."
        },
        {
          "key": "C",
          "text": "Random work depends on chance, while a system creates results by design."
        },
        {
          "key": "D",
          "text": "Systematic work is only necessary for large corporations."
        }
      ],
      "correct": "C",
      "explanation": "The training explicitly contrasts random and systematic work by noting that random work relies entirely on chance, whereas a structured system intentionally creates consistent, predictable results by design"
    },
    {
      "id": 2,
      "question": "According to the module, why do most businesses fail when they lack systems?",
      "choices": [
        {
          "key": "A",
          "text": "Employees are naturally unmotivated and incapable."
        },
        {
          "key": "B",
          "text": "They lack the budget to compete with larger companies."
        },
        {
          "key": "C",
          "text": "They spend too much time reacting to audits."
        },
        {
          "key": "D",
          "text": "There is no clear structure guiding how work should be done, leading to repeated problems and no path to improvement."
        }
      ],
      "correct": "D",
      "explanation": "Businesses fail not due to unmotivated staff, but because lacking a clear, defined structure means there is no reference point to prevent repeating problems or build upon past organizational successes"
    },
    {
      "id": 3,
      "question": "What elements make up an organization's \"Invisible Structure\"?",
      "choices": [
        {
          "key": "A",
          "text": "The physical layout of the office and factory floor."
        },
        {
          "key": "B",
          "text": "Decision-making patterns, task prioritization and flow, and problem-handling habits."
        },
        {
          "key": "C",
          "text": "The final products and services delivered to the customer."
        },
        {
          "key": "D",
          "text": "The formal job titles of the management team."
        }
      ],
      "correct": "B",
      "explanation": "An organization’s invisible structure consists of the underlying rules and habits shaping results, specifically its decision-making patterns, task prioritization and flow, and its habitual approach to handling workplace problems"
    },
    {
      "id": 4,
      "question": "Every effective management system is built on three essential elements. What are they?",
      "choices": [
        {
          "key": "A",
          "text": "People, Process, and Evidence."
        },
        {
          "key": "B",
          "text": "People, Products, and Profits."
        },
        {
          "key": "C",
          "text": "Planning, Production, and Promotion."
        },
        {
          "key": "D",
          "text": "Policy, Procedure, and Purchasing."
        }
      ],
      "correct": "A",
      "explanation": "Every effective management system relies on three interconnected pillars to remain stable: the people performing the work, the processes guiding that work, and the evidence confirming it was done correctly"
    },
    {
      "id": 5,
      "question": "In the context of a management system, what is the purpose of \"Evidence\"?",
      "choices": [
        {
          "key": "A",
          "text": "To find out which employee to blame when things go wrong."
        },
        {
          "key": "B",
          "text": "To define the step-by-step method for how the work is done."
        },
        {
          "key": "C",
          "text": "To serve as the record that proves work was completed correctly, allowing the organization to verify performance."
        },
        {
          "key": "D",
          "text": "To motivate the people performing the work."
        }
      ],
      "correct": "C",
      "explanation": "Evidence serves as the definitive record proving that work was properly completed, enabling the organization to objectively verify performance, identify deviations, and drive targeted improvements based entirely on facts"
    },
    {
      "id": 6,
      "question": "During the journey from \"Chaos to Control,\" at what stage are processes documented, roles defined, and standards begin to take shape?",
      "choices": [
        {
          "key": "A",
          "text": "Stage 1 — Chaos"
        },
        {
          "key": "B",
          "text": "Stage 2 — Awareness"
        },
        {
          "key": "C",
          "text": "Stage 3 — Structure"
        },
        {
          "key": "D",
          "text": "Stage 4 — Control"
        }
      ],
      "correct": "C",
      "explanation": "During Stage 3, known as Structure, organizations transition from mere awareness by actively documenting processes, clearly defining employee roles, and allowing consistent standards to finally take shape across operations"
    },
    {
      "id": 7,
      "question": "When looking at real-world examples of systems on a farm, in a factory, or in an office, what is the key insight?",
      "choices": [
        {
          "key": "A",
          "text": "Systems must be complex to be effective."
        },
        {
          "key": "B",
          "text": "A system is not about complexity — it is about consistency."
        },
        {
          "key": "C",
          "text": "Office environments require vastly different systems than farms."
        },
        {
          "key": "D",
          "text": "Only factories truly benefit from management systems."
        }
      ],
      "correct": "B",
      "explanation": "Whether on a farm, in a factory, or inside an office, the key insight is that a management system does not require complexity; its true purpose is ensuring reliable consistency"
    },
    {
      "id": 8,
      "question": "If a new employee makes errors due to unclear instructions, what does this indicate about the organization?",
      "choices": [
        {
          "key": "A",
          "text": "The organization hired an incapable employee."
        },
        {
          "key": "B",
          "text": "The employee is purposely ignoring the training."
        },
        {
          "key": "C",
          "text": "The problem is caused by a missing or weak system, specifically a lack of structured onboarding."
        },
        {
          "key": "D",
          "text": "The customers are expecting too much from the new hire."
        }
      ],
      "correct": "C",
      "explanation": "When new hires make mistakes due to unclear instructions, it highlights a broken system—specifically the absence of documented guidance and structured onboarding, rather than a lack of employee ability"
    },
    {
      "id": 9,
      "question": "What is the \"New Mindset\" regarding quality in a business?",
      "choices": [
        {
          "key": "A",
          "text": "Quality is an extra responsibility to address when an audit is approaching."
        },
        {
          "key": "B",
          "text": "Quality is a cost, rather than an investment."
        },
        {
          "key": "C",
          "text": "Quality is the foundation of daily operations that delivers consistent value and strengthens trust."
        },
        {
          "key": "D",
          "text": "Quality only applies to the final product, not the daily routines."
        }
      ],
      "correct": "C",
      "explanation": "The new mindset recognizes that quality is not simply an extra task; it is the absolute foundation of daily operations that ensures consistent value, reduces waste, and strengthens customer trust"
    },
    {
      "id": 10,
      "question": "What is the ultimate outcome or goal when you learn to \"See the System\"?",
      "choices": [
        {
          "key": "A",
          "text": "You can stop reacting to problems and start designing better outcomes by intentionally improving the systems."
        },
        {
          "key": "B",
          "text": "You can memorize every standard operating procedure."
        },
        {
          "key": "C",
          "text": "You realize that most outcomes are random and beyond your control."
        },
        {
          "key": "D",
          "text": "You can identify exactly which employee is causing delays."
        }
      ],
      "correct": "A",
      "explanation": "When you finally learn to see the system, you stop merely reacting to symptoms and begin proactively designing better outcomes by intentionally improving the very processes that produce your results"
    }
  ],
  "quality-iso-simplified": [
    {
      "id": 1,
      "question": "According to the training, what does \"quality\" really mean in practical terms?",
      "choices": [
        {
          "key": "A",
          "text": "Being perfect or expensive"
        },
        {
          "key": "B",
          "text": "Meeting expectations consistently"
        },
        {
          "key": "C",
          "text": "Delivering occasional outstanding results"
        },
        {
          "key": "D",
          "text": "Creating the highest-end product regardless of cost"
        }
      ],
      "correct": "B",
      "explanation": "Meeting expectations consistently. Quality is not about perfection or being overly expensive; it is about ensuring the customer gets exactly what they expected and that nothing goes wrong, time after time"
    },
    {
      "id": 2,
      "question": "Which phrase best defines the concept of \"Fitness for Use\"?",
      "choices": [
        {
          "key": "A",
          "text": "The product or service meets defined standards and specifications every time."
        },
        {
          "key": "B",
          "text": "The product or service works as intended in the real conditions it was designed for."
        },
        {
          "key": "C",
          "text": "The business controls its internal operational processes efficiently."
        },
        {
          "key": "D",
          "text": "The organization creates a competitive advantage through lower operating costs."
        }
      ],
      "correct": "B",
      "explanation": "The product or service works as intended in the real conditions it was designed for. This is the specific definition of \"fitness for use,\" distinguishing it from \"conformance to requirements,\" which focuses strictly on meeting defined specifications"
    },
    {
      "id": 3,
      "question": "Which of the following best describes \"Internal Quality\"?",
      "choices": [
        {
          "key": "A",
          "text": "How well the product or service satisfies the end user's desires."
        },
        {
          "key": "B",
          "text": "The overall external reputation and experience of the brand."
        },
        {
          "key": "C",
          "text": "How consistently processes are followed inside the organization."
        },
        {
          "key": "D",
          "text": "The level of customer trust built over a long period of time."
        }
      ],
      "correct": "C",
      "explanation": "How consistently processes are followed inside the organization. Internal quality focuses strictly on systems, internal compliance, operating efficiency, and doing things correctly every time, rather than the direct, external end-user experience"
    },
    {
      "id": 4,
      "question": "Which of the following is considered a \"Cost of Good Quality\"?",
      "choices": [
        {
          "key": "A",
          "text": "Expenses related to failures and unforced errors."
        },
        {
          "key": "B",
          "text": "Handling returned products and repairing damaged customer relationships."
        },
        {
          "key": "C",
          "text": "Investments in training, inspections, and prevention activities."
        },
        {
          "key": "D",
          "text": "Operational waste, delays, and necessary rework."
        }
      ],
      "correct": "C",
      "explanation": "Investments in training, inspections, and prevention activities. These are proactive, necessary investments designed to stop defects before they happen, whereas failures, returns, and waste represent the damaging cost of poor quality"
    },
    {
      "id": 5,
      "question": "What is the fundamental financial rule regarding the cost of quality?",
      "choices": [
        {
          "key": "A",
          "text": "It is always cheaper to prevent problems than to fix them after they occur."
        },
        {
          "key": "B",
          "text": "Fixing problems builds a stronger bond with the customer over time."
        },
        {
          "key": "C",
          "text": "High quality always costs more money than poor quality in the long run."
        },
        {
          "key": "D",
          "text": "Prevention activities are an unnecessary financial burden for most businesses."
        }
      ],
      "correct": "A",
      "explanation": "It is always cheaper to prevent problems than to fix them after they occur. Organizations that invest heavily in prevention significantly reduce long-term failures, turning quality into a powerful financial advantage rather than a costly business burden"
    },
    {
      "id": 6,
      "question": "When building trust with customers, what is more valuable than an occasional outstanding result?",
      "choices": [
        {
          "key": "A",
          "text": "A highly memorable, stand-alone advertisement."
        },
        {
          "key": "B",
          "text": "Consistent performance delivered the exact same way every time."
        },
        {
          "key": "C",
          "text": "Offering significant discounts whenever operational mistakes happen."
        },
        {
          "key": "D",
          "text": "Having the fastest possible response time when issuing apologies."
        }
      ],
      "correct": "B",
      "explanation": "Consistent performance delivered the exact same way every time. Customers inherently remember reliable patterns rather than isolated moments of brilliance; steady reliability is the true foundation for building lasting trust and strong relationships"
    },
    {
      "id": 7,
      "question": "How should an organization view the ISO 9001 standard?",
      "choices": [
        {
          "key": "A",
          "text": "As a complicated rulebook that dictates every daily action."
        },
        {
          "key": "B",
          "text": "As a structured framework for building a system that works reliably."
        },
        {
          "key": "C",
          "text": "As a highly specific, step-by-step instruction manual for running a business."
        },
        {
          "key": "D",
          "text": "As a mandatory set of paperwork designed only for external auditors."
        }
      ],
      "correct": "B",
      "explanation": "As a structured framework for building a system that works reliably. ISO 9001 does not dictate exactly how to run your unique business; instead, it provides the vital architecture needed to consistently deliver quality outcomes"
    },
    {
      "id": 8,
      "question": "Which of the following is one of the 7 Principles of Quality Management?",
      "choices": [
        {
          "key": "A",
          "text": "Occasional Brilliance"
        },
        {
          "key": "B",
          "text": "Maximizing Profit"
        },
        {
          "key": "C",
          "text": "Evidence-Based Decisions"
        },
        {
          "key": "D",
          "text": "Eliminating Documentation"
        }
      ],
      "correct": "C",
      "explanation": "Evidence-Based Decisions. Quality is never accidental and relies on powerful guiding principles like evidence-based decisions, ensuring that important organizational choices are properly grounded in actual data and analysis"
    },
    {
      "id": 9,
      "question": "What is the true practical purpose of documentation in a quality management system?",
      "choices": [
        {
          "key": "A",
          "text": "To create mountains of forms to look busy."
        },
        {
          "key": "B",
          "text": "To satisfy the requirements of external regulatory agencies only."
        },
        {
          "key": "C",
          "text": "To support clarity, consistency, and accountability in everyday work."
        },
        {
          "key": "D",
          "text": "To intentionally slow down the work process so mistakes aren't made."
        }
      ],
      "correct": "C",
      "explanation": "To support clarity, consistency, and accountability in everyday work. Documentation is not merely paperwork for its own sake; it effectively removes ambiguity, ensures repeatable work, and makes it possible to trace problems to their root causes"
    },
    {
      "id": 10,
      "question": "How should an organization integrate quality into a product or service?",
      "choices": [
        {
          "key": "A",
          "text": "It should be strictly inspected at the very end of the line."
        },
        {
          "key": "B",
          "text": "It should be built into the system from the very start."
        },
        {
          "key": "C",
          "text": "It should be added to the process only if a customer complains."
        },
        {
          "key": "D",
          "text": "It should be the sole, isolated responsibility of the quality control department."
        }
      ],
      "correct": "B",
      "explanation": "It should be built into the system from the very start. Quality cannot simply be inspected into a product at the end of a process; it must be intelligently designed into the very systems that create the outcome"
    }
  ],
  "process-thinking": [
    {
      "id": 1,
      "question": "What is the fundamental purpose of process thinking within a Quality Management System?",
      "choices": [
        {
          "key": "A",
          "text": "To create more administrative tasks for employees"
        },
        {
          "key": "B",
          "text": "To transform good intentions into consistent results"
        },
        {
          "key": "C",
          "text": "To replace human workers with automation"
        },
        {
          "key": "D",
          "text": "To eliminate the need for process owners"
        }
      ],
      "correct": "B",
      "explanation": "Process thinking serves as the foundation of an effective QMS by shifting focus to how work truly flows, transforming initial good intentions into predictable, consistent outcomes"
    },
    {
      "id": 2,
      "question": "What is the crucial distinction between a \"task\" and a \"process\"?",
      "choices": [
        {
          "key": "A",
          "text": "A process is done by management, while a task is done by workers."
        },
        {
          "key": "B",
          "text": "Tasks require inputs, but a process does not."
        },
        {
          "key": "C",
          "text": "Tasks in isolation produce effort, while connected tasks produce outcomes."
        },
        {
          "key": "D",
          "text": "Tasks are strictly documented, but processes are informal."
        }
      ],
      "correct": "C",
      "explanation": "While isolated tasks only generate standalone effort, a process connects these individual tasks into a sequence that actually produces a meaningful outcome or result"
    },
    {
      "id": 3,
      "question": "According to the \"Input → Activity → Output\" structure, where does the issue lie if the final output is wrong?",
      "choices": [
        {
          "key": "A",
          "text": "In the initial input or the activity itself."
        },
        {
          "key": "B",
          "text": "Usually somewhere outside the process."
        },
        {
          "key": "C",
          "text": "Solely in the customer's unrealistic expectations."
        },
        {
          "key": "D",
          "text": "In the support processes only."
        }
      ],
      "correct": "A",
      "explanation": "If an output is incorrect, the root cause is never outside the workflow; it is always found in either the starting input or the transformative activity steps"
    },
    {
      "id": 4,
      "question": "What question defines the \"Flow Mindset\" as opposed to the \"Task Mindset\"?",
      "choices": [
        {
          "key": "A",
          "text": "\"What am I doing right now?\""
        },
        {
          "key": "B",
          "text": "\"How can I finish this as fast as possible?\""
        },
        {
          "key": "C",
          "text": "\"How does this connect to everything else?\""
        },
        {
          "key": "D",
          "text": "\"Who can I hand this off to?\""
        }
      ],
      "correct": "C",
      "explanation": "A flow mindset recognizes that steps depend on each other, shifting the focus from isolated actions to asking how every individual step connects to the larger system"
    },
    {
      "id": 5,
      "question": "What is a key insight regarding process mapping?",
      "choices": [
        {
          "key": "A",
          "text": "You need complex software to map a process accurately."
        },
        {
          "key": "B",
          "text": "If you cannot draw the process, you do not fully understand it yet."
        },
        {
          "key": "C",
          "text": "Written procedures are always more insightful than visual maps."
        },
        {
          "key": "D",
          "text": "It is a tool used strictly to define process owners."
        }
      ],
      "correct": "B",
      "explanation": "Process mapping reveals insights written text cannot. The module's key insight states that if you are unable to visually sketch the workflow, your understanding of it remains incomplete"
    },
    {
      "id": 6,
      "question": "What does the acronym SIPOC stand for?",
      "choices": [
        {
          "key": "A",
          "text": "System, Input, Procedure, Output, Control"
        },
        {
          "key": "B",
          "text": "Standard, Inspection, Process, Outcome, Correction"
        },
        {
          "key": "C",
          "text": "Supplier, Integration, Planning, Output, Communication"
        },
        {
          "key": "D",
          "text": "Supplier, Input, Process, Output, Customer"
        }
      ],
      "correct": "D",
      "explanation": "SIPOC is a high-level visual tool standing for Supplier, Input, Process, Output, and Customer, effectively demonstrating how these five elements connect people, materials, and final outcomes"
    },
    {
      "id": 7,
      "question": "Which of the following best describes a \"Core Process\"?",
      "choices": [
        {
          "key": "A",
          "text": "A process like HR or IT that helps other functions."
        },
        {
          "key": "B",
          "text": "A process that does not deliver value directly to the customer."
        },
        {
          "key": "C",
          "text": "A process that directly creates value for the customer."
        },
        {
          "key": "D",
          "text": "A process that exists solely to support QMS documentation."
        }
      ],
      "correct": "C",
      "explanation": "Core processes, such as production or order fulfillment, directly create the value the customer pays for, whereas support processes (like IT or HR) merely enable those core processes"
    },
    {
      "id": 8,
      "question": "Why is it essential to have a clearly defined \"Process Owner\"?",
      "choices": [
        {
          "key": "A",
          "text": "Because if everyone is responsible, no one is responsible."
        },
        {
          "key": "B",
          "text": "So one person can execute all the manual labor themselves."
        },
        {
          "key": "C",
          "text": "To ensure workflows are never altered once established."
        },
        {
          "key": "D",
          "text": "Because every individual task requires a designated executive."
        }
      ],
      "correct": "A",
      "explanation": "Ownership must be explicitly assigned rather than assumed because shared responsibility often means no one takes actual accountability to ensure the process is defined, followed, and improved"
    },
    {
      "id": 9,
      "question": "How does a bottleneck affect an entire process?",
      "choices": [
        {
          "key": "A",
          "text": "It increases the overall speed of the system."
        },
        {
          "key": "B",
          "text": "The weakest step limits the performance and sets the pace for the whole system."
        },
        {
          "key": "C",
          "text": "It permanently eliminates process variation."
        },
        {
          "key": "D",
          "text": "It only impacts support processes, not core processes."
        }
      ],
      "correct": "B",
      "explanation": "A bottleneck is a constraint where work slows down; regardless of how fast other parts operate, this slowest step dictates the overall speed and performance of the entire system"
    },
    {
      "id": 10,
      "question": "How is \"process thinking\" described in the final module summary?",
      "choices": [
        {
          "key": "A",
          "text": "It is just a visual tool for management."
        },
        {
          "key": "B",
          "text": "It is a complex framework requiring formal training."
        },
        {
          "key": "C",
          "text": "It is only applicable to manufacturing pipelines."
        },
        {
          "key": "D",
          "text": "It is not a tool — it is a new way of seeing."
        }
      ],
      "correct": "D",
      "explanation": "The module emphasizes that understanding workflow gives you the power to control and improve it, framing process thinking as a fundamental \"new way of seeing\" rather than a mere tool"
    }
  ],
  "risk-based-thinking": [
    {
      "id": 1,
      "question": "What is the best definition of \"risk\" in the context of this module?",
      "choices": [
        {
          "key": "A",
          "text": "A confirmed problem that requires immediate fixing"
        },
        {
          "key": "B",
          "text": "The possibility that something may go wrong and affect your result"
        },
        {
          "key": "C",
          "text": "A physical object that causes immediate harm"
        },
        {
          "key": "D",
          "text": "A regulatory fine from a compliance audit"
        }
      ],
      "correct": "B",
      "explanation": "Risk is fundamentally about uncertainty; it is not the problem itself, but rather the chance that a problem or negative outcome could happen in a given process"
    },
    {
      "id": 2,
      "question": "Which of the following best describes the difference between a hazard and a risk?",
      "choices": [
        {
          "key": "A",
          "text": "A hazard is the chance of harm, while risk is the source of the harm."
        },
        {
          "key": "B",
          "text": "A hazard is an equipment failure, while risk is human error."
        },
        {
          "key": "C",
          "text": "A hazard is the source of potential harm, while risk is the likelihood and seriousness of that harm occurring."
        },
        {
          "key": "D",
          "text": "There is no difference; the terms mean exactly the same thing."
        }
      ],
      "correct": "C",
      "explanation": "A hazard is the actual source of potential harm (like a wet floor), whereas risk combines the likelihood of that harm happening with how serious the impact would be"
    },
    {
      "id": 3,
      "question": "Why does \"prevention beat correction\" in risk-based thinking?",
      "choices": [
        {
          "key": "A",
          "text": "Fixing problems after they occur is always cheaper."
        },
        {
          "key": "B",
          "text": "Prevention creates stability, whereas correction only restores it after time and money are lost."
        },
        {
          "key": "C",
          "text": "Corrective actions are easier to document for compliance audits."
        },
        {
          "key": "D",
          "text": "Prevention guarantees that equipment will never break down."
        }
      ],
      "correct": "B",
      "explanation": "Prevention is proactive and protects quality and trust. Correcting problems after they happen drains resources and disrupts operations, making it more expensive and less stable than stopping them early"
    },
    {
      "id": 4,
      "question": "When identifying risks in daily work, which of the following is considered a source of risk related to \"Environment\"?",
      "choices": [
        {
          "key": "A",
          "text": "Skill gaps and fatigue"
        },
        {
          "key": "B",
          "text": "Wear and miscalibration"
        },
        {
          "key": "C",
          "text": "Unclear steps and poor sequencing"
        },
        {
          "key": "D",
          "text": "Temperature, lighting, and noise"
        }
      ],
      "correct": "D",
      "explanation": "Risks originate from four primary areas: people, processes, equipment, and the environment. Factors like temperature, lighting, noise, and workspace layout are explicitly categorized as environmental sources of risk"
    },
    {
      "id": 5,
      "question": "Which set of three questions should you ask to build the habit of finding risks before they cause damage?",
      "choices": [
        {
          "key": "A",
          "text": "Who is to blame? How much will it cost? When can we fix it?"
        },
        {
          "key": "B",
          "text": "What could go wrong? Why could it go wrong? What would happen if it did?"
        },
        {
          "key": "C",
          "text": "Is this a hazard? Is this a risk? Is this an incident?"
        },
        {
          "key": "D",
          "text": "Has this happened before? Who noticed it? Is it documented?"
        }
      ],
      "correct": "B",
      "explanation": "To effectively identify risks, you should evaluate your daily activities by asking: \"What could go wrong?\", \"Why could it go wrong?\", and \"What would happen if it did?\""
    },
    {
      "id": 6,
      "question": "When using a simple risk scoring tool, which two dimensions are used to determine a risk's priority?",
      "choices": [
        {
          "key": "A",
          "text": "Cost and Time"
        },
        {
          "key": "B",
          "text": "Likelihood and Severity"
        },
        {
          "key": "C",
          "text": "Frequency and Location"
        },
        {
          "key": "D",
          "text": "People and Processes"
        }
      ],
      "correct": "B",
      "explanation": "To prioritize which risks need the most attention, they are scored based on two main dimensions: how often they might happen (likelihood) and how serious the resulting impact is (severity)"
    },
    {
      "id": 7,
      "question": "According to the risk scoring matrix, what action should you take for a risk that has both a \"High Likelihood\" and \"High Severity\"?",
      "choices": [
        {
          "key": "A",
          "text": "Monitor Closely"
        },
        {
          "key": "B",
          "text": "Low Priority"
        },
        {
          "key": "C",
          "text": "Manage Routinely"
        },
        {
          "key": "D",
          "text": "Act Immediately"
        }
      ],
      "correct": "D",
      "explanation": "When combining likelihood and severity scores on the matrix, any risk that scores high in both of these dimensions requires you to \"Act Immediately\" to prevent a major failure"
    },
    {
      "id": 8,
      "question": "Physical or automated barriers that prevent dangerous conditions from occurring are an example of which type of control?",
      "choices": [
        {
          "key": "A",
          "text": "Clear Procedures"
        },
        {
          "key": "B",
          "text": "Equipment Safeguards"
        },
        {
          "key": "C",
          "text": "Training"
        },
        {
          "key": "D",
          "text": "Checklists & Inspections"
        }
      ],
      "correct": "B",
      "explanation": "Equipment safeguards are specifically defined as physical or automated barriers designed to prevent dangerous conditions, which is a key method for putting controls and mitigations in place"
    },
    {
      "id": 9,
      "question": "How does risk-based thinking support an organisation's legal and compliance requirements?",
      "choices": [
        {
          "key": "A",
          "text": "It ensures requirements are built into daily processes rather than treated as a once-a-year checklist."
        },
        {
          "key": "B",
          "text": "It replaces the need for any safety or environmental regulations."
        },
        {
          "key": "C",
          "text": "It guarantees that a company will never face a lawsuit or fine."
        },
        {
          "key": "D",
          "text": "It allows an organisation to bypass audits if their risk score is low enough."
        }
      ],
      "correct": "A",
      "explanation": "Risk-based thinking helps ensure compliance by building regulatory standards directly into everyday workflows. This makes compliance a daily habit rather than a separate activity done only during audits"
    },
    {
      "id": 10,
      "question": "In the \"Product for Delivery\" scenario, which of the following is identified as a potential risk?",
      "choices": [
        {
          "key": "A",
          "text": "A wet floor in the warehouse"
        },
        {
          "key": "B",
          "text": "Incorrect labeling with the wrong product or address"
        },
        {
          "key": "C",
          "text": "Uncalibrated manufacturing machinery"
        },
        {
          "key": "D",
          "text": "Poor workspace lighting"
        }
      ],
      "correct": "B",
      "explanation": "During the delivery preparation risk-spotting exercise, incorrect labeling, damaged packaging, missing items, and delayed dispatch are specifically listed as the potential risks that need to be analyzed"
    }
  ],
  "documentation-works": [
    {
      "id": 1,
      "question": "What is the primary reason documentation exists in the workplace?",
      "choices": [
        {
          "key": "A",
          "text": "To add extra administrative work for supervisors"
        },
        {
          "key": "B",
          "text": "To make work clear, consistent, and repeatable"
        },
        {
          "key": "C",
          "text": "To make training take longer"
        },
        {
          "key": "D",
          "text": "To replace hands-on managers"
        }
      ],
      "correct": "B",
      "explanation": ") To make work clear, consistent, and repeatable. Explanation: Documentation does not exist to add extra work; it removes confusion and ensures everyone understands how to complete tasks consistently to the expected standard, making results reliable"
    },
    {
      "id": 2,
      "question": "Which type of document is designed to provide step-by-step instructions for how work is done?",
      "choices": [
        {
          "key": "A",
          "text": "Policies"
        },
        {
          "key": "B",
          "text": "Records"
        },
        {
          "key": "C",
          "text": "Standard Operating Procedures (SOPs)"
        },
        {
          "key": "D",
          "text": "Change Records"
        }
      ],
      "correct": "C",
      "explanation": ") Standard Operating Procedures (SOPs). Explanation: SOPs specifically instruct action by providing clear, step-by-step instructions for the \"how\" of a task, whereas policies guide direction and records prove completion"
    },
    {
      "id": 3,
      "question": "What is the main purpose of a \"Record\"?",
      "choices": [
        {
          "key": "A",
          "text": "To guide the organization's direction and beliefs"
        },
        {
          "key": "B",
          "text": "To provide a visual diagram of a task"
        },
        {
          "key": "C",
          "text": "To provide evidence and prove that work was completed"
        },
        {
          "key": "D",
          "text": "To communicate upcoming changes to the team"
        }
      ],
      "correct": "C",
      "explanation": ") To provide evidence and prove that work was completed. Explanation: Records prove completion. They serve as tangible evidence that a task was achieved, providing \"the what happened\" necessary to verify results during audits and investigations"
    },
    {
      "id": 4,
      "question": "According to the guidelines for writing simple SOPs, who should the language be written for?",
      "choices": [
        {
          "key": "A",
          "text": "The person doing the work"
        },
        {
          "key": "B",
          "text": "The manager reviewing the document"
        },
        {
          "key": "C",
          "text": "External auditors"
        },
        {
          "key": "D",
          "text": "The company CEO"
        }
      ],
      "correct": "A",
      "explanation": ") The person doing the work. Explanation: A good, simple SOP uses plain language tailored specifically for the frontline worker performing the task, rather than a manager or auditor reviewing the document"
    },
    {
      "id": 5,
      "question": "What is an effective way to simplify document design for all literacy levels?",
      "choices": [
        {
          "key": "A",
          "text": "Writing longer paragraphs"
        },
        {
          "key": "B",
          "text": "Using visuals like diagrams, icons, and symbols"
        },
        {
          "key": "C",
          "text": "Removing all spacing and formatting"
        },
        {
          "key": "D",
          "text": "Using complex vocabulary and jargon"
        }
      ],
      "correct": "B",
      "explanation": ") Using visuals like diagrams, icons, and symbols. Explanation: Visuals such as diagrams, flowcharts, and icons replace long blocks of text, making instructions easier to understand quickly across all learning and literacy levels"
    },
    {
      "id": 6,
      "question": "Which of the following is ONE of the \"Four Pillars of Document Control\"?",
      "choices": [
        {
          "key": "A",
          "text": "Unapproved drafts can be used as official SOPs"
        },
        {
          "key": "B",
          "text": "Documents are kept in locked cabinets away from the point of work"
        },
        {
          "key": "C",
          "text": "Outdated versions are removed or archived immediately"
        },
        {
          "key": "D",
          "text": "Changes are kept secret until audits occur"
        }
      ],
      "correct": "C",
      "explanation": ") Outdated versions are removed or archived immediately. Explanation: To maintain control and prevent workers from following incorrect instructions, old versions must be removed or archived the moment an update is released"
    },
    {
      "id": 7,
      "question": "Why is it important to control document versions?",
      "choices": [
        {
          "key": "A",
          "text": "So different people can follow different processes"
        },
        {
          "key": "B",
          "text": "To prevent confusion, inconsistency, and risk"
        },
        {
          "key": "C",
          "text": "Because it adds a decorative element to the page"
        },
        {
          "key": "D",
          "text": "So outdated instructions remain easily accessible"
        }
      ],
      "correct": "B",
      "explanation": ") To prevent confusion, inconsistency, and risk. Explanation: Without version control, different people may follow different iterations of the same process. Controlling versions ensures predictability and eliminates the chaos of uncontrolled processes"
    },
    {
      "id": 8,
      "question": "What three elements are essential for effective Version Control?",
      "choices": [
        {
          "key": "A",
          "text": "Version number, Date of update, and Change record"
        },
        {
          "key": "B",
          "text": "Author name, Signature, and Department"
        },
        {
          "key": "C",
          "text": "Font size, Color, and Layout"
        },
        {
          "key": "D",
          "text": "Policy, SOP, and Record"
        }
      ],
      "correct": "A",
      "explanation": ") Version number, Date of update, and Change record. Explanation: These three elements prevent chaos by showing the document iteration, confirming it reflects current practice, and summarizing what changed to maintain a traceable history"
    },
    {
      "id": 9,
      "question": "Why are records described as \"protection\"?",
      "choices": [
        {
          "key": "A",
          "text": "They hide mistakes from regulators"
        },
        {
          "key": "B",
          "text": "They prove that work was done correctly and to standard"
        },
        {
          "key": "C",
          "text": "They act as legal waivers to avoid safety protocols"
        },
        {
          "key": "D",
          "text": "They slow down the investigation process"
        }
      ],
      "correct": "B",
      "explanation": ") They prove that work was done correctly and to standard. Explanation: Records are protection because they provide concrete proof of what actually happened, showing regulators and auditors that work met standards, while also establishing team accountability"
    },
    {
      "id": 10,
      "question": "Why does an instruction like \"Do the task properly\" fail in an SOP?",
      "choices": [
        {
          "key": "A",
          "text": "It is too long to read quickly"
        },
        {
          "key": "B",
          "text": "It includes too many checklists"
        },
        {
          "key": "C",
          "text": "It is too specific and restrictive"
        },
        {
          "key": "D",
          "text": "It does not define what \"properly\" means, leading to inconsistent interpretations"
        }
      ],
      "correct": "D",
      "explanation": ") It does not define what \"properly\" means, leading to inconsistent interpretations. Explanation: Subjective words like \"properly\" leave instructions open to interpretation. Everyone will execute the task differently, which ultimately leads to inconsistent outcomes and a lack of accountability"
    }
  ],
  "people-drive-quality": [
    {
      "id": 1,
      "question": "Based on the module, what is the relationship between systems and people?",
      "choices": [
        {
          "key": "A",
          "text": "Systems operate independently of human action."
        },
        {
          "key": "B",
          "text": "People are only needed when systems fail."
        },
        {
          "key": "C",
          "text": "Systems only work when people understand and care about the outcome."
        },
        {
          "key": "D",
          "text": "Perfect system design guarantees flawless execution."
        }
      ],
      "correct": "C",
      "explanation": "A system can be perfectly designed, but it will still fail if the people executing it do not understand, follow, or care about the final outcome"
    },
    {
      "id": 2,
      "question": "What is the primary difference between training and competence?",
      "choices": [
        {
          "key": "A",
          "text": "Training requires applied skill, while competence requires only exposure."
        },
        {
          "key": "B",
          "text": "Training delivers information, while competence is the demonstrated ability to produce consistent results."
        },
        {
          "key": "C",
          "text": "Training takes longer to complete than building competence."
        },
        {
          "key": "D",
          "text": "They are identical terms in quality management."
        }
      ],
      "correct": "B",
      "explanation": "Training only provides information and exposure. Competence requires knowledge, applied skill, and verified experience to consistently perform a task correctly over time"
    },
    {
      "id": 3,
      "question": "How is \"compliance\" different from true \"behavior\" in an organization?",
      "choices": [
        {
          "key": "A",
          "text": "Compliance is what people do when no one is watching, behavior is rule-following for audits."
        },
        {
          "key": "B",
          "text": "Compliance is surface-level rule-following, while behavior reflects genuine everyday actions."
        },
        {
          "key": "C",
          "text": "Compliance requires leadership investment, but behavior happens automatically."
        },
        {
          "key": "D",
          "text": "Compliance applies to managers, behavior applies to floor workers."
        }
      ],
      "correct": "B",
      "explanation": "Compliance is following rules just because you are monitored. Behavior is what people genuinely do under everyday conditions, especially when nobody is actively watching them"
    },
    {
      "id": 4,
      "question": "What two elements create a \"reinforcing loop\" in an organization?",
      "choices": [
        {
          "key": "A",
          "text": "Training and auditing"
        },
        {
          "key": "B",
          "text": "Culture and accountability"
        },
        {
          "key": "C",
          "text": "Speed targets and quality goals"
        },
        {
          "key": "D",
          "text": "Motivation and compliance"
        }
      ],
      "correct": "B",
      "explanation": "Culture dictates how people think and act, while accountability ensures people own their results. These two forces continually reinforce and strengthen one another"
    },
    {
      "id": 5,
      "question": "How do leaders build credibility and effectively embed quality into daily operations?",
      "choices": [
        {
          "key": "A",
          "text": "By issuing more quality directives and policies."
        },
        {
          "key": "B",
          "text": "By rushing past quality to hit speed targets."
        },
        {
          "key": "C",
          "text": "By demonstrating expectations through everyday actions and decisions."
        },
        {
          "key": "D",
          "text": "By blaming floor workers for systemic failures."
        }
      ],
      "correct": "C",
      "explanation": "People follow what leaders do, not what they say. Showing commitment through consistent action—like prioritizing quality over speed—effectively embeds these values into daily operations"
    },
    {
      "id": 6,
      "question": "A strong communication system must include \"feedback loops.\" What does this mean?",
      "choices": [
        {
          "key": "A",
          "text": "Teams only receive top-down instructions from management."
        },
        {
          "key": "B",
          "text": "Employees must repeat instructions back to managers verbatim."
        },
        {
          "key": "C",
          "text": "Communication is two-directional, allowing teams to flag errors without fear."
        },
        {
          "key": "D",
          "text": "Messages are passed through an automated system to track errors."
        }
      ],
      "correct": "C",
      "explanation": "Effective communication systems must be two-directional. Teams need structured, safe channels to escalate issues, report errors, and offer feedback without fearing negative consequences from management"
    },
    {
      "id": 7,
      "question": "According to the module, clarity removes uncertainty. What does clarity build?",
      "choices": [
        {
          "key": "A",
          "text": "Purpose"
        },
        {
          "key": "B",
          "text": "Motivation"
        },
        {
          "key": "C",
          "text": "Confidence"
        },
        {
          "key": "D",
          "text": "Compliance"
        }
      ],
      "correct": "C",
      "explanation": "While purpose builds motivation, clarity builds confidence. When employees clearly know what is expected and how to do it, they act with much greater certainty and skill"
    },
    {
      "id": 8,
      "question": "What drives \"motivation\" in the workplace?",
      "choices": [
        {
          "key": "A",
          "text": "Strict auditing and compliance checks."
        },
        {
          "key": "B",
          "text": "Knowing exactly what the process is."
        },
        {
          "key": "C",
          "text": "Understanding the purpose of the work and why it matters."
        },
        {
          "key": "D",
          "text": "Receiving an updated manual."
        }
      ],
      "correct": "C",
      "explanation": "Motivation is directly driven by purpose. When individuals truly understand why their work matters and how it connects to larger outcomes, they naturally develop the drive to engage"
    },
    {
      "id": 9,
      "question": "In the role-play scenario \"The Ignored Error,\" a supervisor sees a mistake but ignores it to avoid slowing production. What key insight does this demonstrate?",
      "choices": [
        {
          "key": "A",
          "text": "Behavior is shaped by what leaders allow and ignore."
        },
        {
          "key": "B",
          "text": "Quality should always take a backseat to production speed."
        },
        {
          "key": "C",
          "text": "Workers are responsible for all unaddressed errors."
        },
        {
          "key": "D",
          "text": "The communication system is functioning perfectly."
        }
      ],
      "correct": "A",
      "explanation": "This scenario shows that employee and supervisor behavior is shaped by the surrounding system. A culture is defined by what leadership explicitly rewards, allows, or chooses to ignore"
    },
    {
      "id": 10,
      "question": "Which statement best captures the final conclusion of the module?",
      "choices": [
        {
          "key": "A",
          "text": "Perfect documentation replaces the need for skilled operators."
        },
        {
          "key": "B",
          "text": "Systems exist separately from the people who operate them."
        },
        {
          "key": "C",
          "text": "\"People are the system,\" as controls only work when used correctly."
        },
        {
          "key": "D",
          "text": "Paper compliance is the ultimate goal of a quality system."
        }
      ],
      "correct": "C",
      "explanation": "The module concludes that \"people are the system.\" Processes and documents are meaningless unless the people operating them do so with intention, genuine understanding, and clear communication"
    }
  ],
  "monitoring-measurement": [
    {
      "id": 1,
      "question": "Why is measurement considered essential in any system according to the module?",
      "choices": [
        {
          "key": "A",
          "text": "It guarantees an immediate increase in profits."
        },
        {
          "key": "B",
          "text": "You cannot improve what you do not measure."
        },
        {
          "key": "C",
          "text": "It makes the organization look impressive to customers."
        },
        {
          "key": "D",
          "text": "It completely replaces the need for critical thinking."
        }
      ],
      "correct": "B",
      "explanation": "- The module states that invisible performance cannot be managed. Measurement makes problems visible early, tracking performance over time so that decisions are grounded in facts, not guesses"
    },
    {
      "id": 2,
      "question": "What is the primary characteristic of a \"good metric\"?",
      "choices": [
        {
          "key": "A",
          "text": "It is vague and broadly defined."
        },
        {
          "key": "B",
          "text": "It looks impressive on a reporting dashboard."
        },
        {
          "key": "C",
          "text": "It helps you take actionable steps."
        },
        {
          "key": "D",
          "text": "It is entirely unrelated to specific outcomes."
        }
      ],
      "correct": "C",
      "explanation": "- A metric is only useful if it helps guide improvement actions. Good metrics are clear, specific, directly linked to outcomes, and highlight real problems rather than just looking impressive"
    },
    {
      "id": 3,
      "question": "Which of the following is an example of a lagging indicator?",
      "choices": [
        {
          "key": "A",
          "text": "Training sessions conducted"
        },
        {
          "key": "B",
          "text": "Equipment maintenance compliance"
        },
        {
          "key": "C",
          "text": "Process checks completed per shift"
        },
        {
          "key": "D",
          "text": "Customer complaints received"
        }
      ],
      "correct": "D",
      "explanation": "- Customer complaints, monthly return rates, and end-of-production defects measure results after an event has occurred, which makes them lagging indicators that are useful for reporting but late for prevention"
    },
    {
      "id": 4,
      "question": "What is the main purpose of a leading indicator?",
      "choices": [
        {
          "key": "A",
          "text": "To measure results after an event has completely finished"
        },
        {
          "key": "B",
          "text": "To influence future outcomes and prevent problems before they appear"
        },
        {
          "key": "C",
          "text": "To confirm whether a past production goal was met"
        },
        {
          "key": "D",
          "text": "To report on the monthly return rate to management"
        }
      ],
      "correct": "B",
      "explanation": "- Leading indicators measure factors that influence future outcomes, such as training or maintenance. This gives teams the opportunity to intervene early and proactively prevent problems before they actually occur"
    },
    {
      "id": 5,
      "question": "In the context of Key Performance Indicators (KPIs), what does \"Process Cycle Time\" measure?",
      "choices": [
        {
          "key": "A",
          "text": "The proportion of output that fails quality standards"
        },
        {
          "key": "B",
          "text": "How long it takes to complete one unit of work from start to finish"
        },
        {
          "key": "C",
          "text": "Whether products reach customers exactly as promised"
        },
        {
          "key": "D",
          "text": "The direct signal of overall customer experience"
        }
      ],
      "correct": "B",
      "explanation": "- According to the KPIs guide, Process Cycle Time tracks how long it takes to complete one unit of work from start to finish, reflecting overall process efficiency and speed"
    },
    {
      "id": 6,
      "question": "What is the crucial step required to turn collected \"Data\" into actionable \"Insight\"?",
      "choices": [
        {
          "key": "A",
          "text": "Analysis"
        },
        {
          "key": "B",
          "text": "Guesswork"
        },
        {
          "key": "C",
          "text": "Ignoring anomalies"
        },
        {
          "key": "D",
          "text": "Creating lagging indicators"
        }
      ],
      "correct": "A",
      "explanation": "- Data alone does not create value. It requires analysis to identify patterns, trends, and anomalies so that teams can understand what is happening and why, turning data into insight"
    },
    {
      "id": 7,
      "question": "When making decisions using data, what should you do immediately after identifying the problem?",
      "choices": [
        {
          "key": "A",
          "text": "Implement a Solution"
        },
        {
          "key": "B",
          "text": "Validate the Result"
        },
        {
          "key": "C",
          "text": "Analyze the Root Cause"
        },
        {
          "key": "D",
          "text": "Change your Key Performance Indicators"
        }
      ],
      "correct": "C",
      "explanation": "- In the decision-making framework, once data highlights a performance deviation (Identifying the Problem), the immediate next step is to Analyze the Root Cause by observing patterns driving the issue"
    },
    {
      "id": 8,
      "question": "What is a common pitfall of relying on a \"bad metric\"?",
      "choices": [
        {
          "key": "A",
          "text": "It accurately highlights real, underlying problems."
        },
        {
          "key": "B",
          "text": "It reliably guides improvement actions for the team."
        },
        {
          "key": "C",
          "text": "It may look impressive but mislead teams with a false sense of progress."
        },
        {
          "key": "D",
          "text": "It is directly linked to specific business outcomes."
        }
      ],
      "correct": "C",
      "explanation": "- Bad metrics can create a false sense of progress because they are often vague, unrelated to actual results, or look impressive while entirely failing to support actionable decision-making"
    },
    {
      "id": 9,
      "question": "According to the module, numbers alone can mislead. What must always be combined with data analysis?",
      "choices": [
        {
          "key": "A",
          "text": "Process knowledge and critical thinking"
        },
        {
          "key": "B",
          "text": "Assumptions and unverified opinions"
        },
        {
          "key": "C",
          "text": "Guesswork and incomplete information"
        },
        {
          "key": "D",
          "text": "Vague and ambiguous performance indicators"
        }
      ],
      "correct": "A",
      "explanation": "- Data guides decisions but does not replace thinking. Because numbers interpreted without proper context can mislead, they must always be combined with practical process knowledge and critical thinking"
    },
    {
      "id": 10,
      "question": "What is the final step in the data-driven decision-making process to confirm an improvement actually worked?",
      "choices": [
        {
          "key": "A",
          "text": "Identify the Problem"
        },
        {
          "key": "B",
          "text": "Analyze Root Cause"
        },
        {
          "key": "C",
          "text": "Validate the Result"
        },
        {
          "key": "D",
          "text": "Implement a Solution"
        }
      ],
      "correct": "C",
      "explanation": "- After successfully implementing a solution, organizations must Validate the Result. This means looking at post-change data to confidently verify with evidence that the corrective action actually worked as intended"
    }
  ],
  "audits-capa": [
    {
      "id": 1,
      "question": "What is a major consequence of treating audits as a way to assign blame?",
      "choices": [
        {
          "key": "A",
          "text": "It encourages open reporting without fear."
        },
        {
          "key": "B",
          "text": "It causes problems to go unreported so people can avoid consequences."
        },
        {
          "key": "C",
          "text": "It permanently resolves identified gaps."
        },
        {
          "key": "D",
          "text": "It creates the conditions for real improvement."
        }
      ],
      "correct": "B",
      "explanation": "The \"Blame Approach\" makes people fear punishment, leading them to hide mistakes"
    },
    {
      "id": 2,
      "question": "Which of the following best describes the primary purpose of an internal audit?",
      "choices": [
        {
          "key": "A",
          "text": "To independently verify compliance for regulatory bodies."
        },
        {
          "key": "B",
          "text": "To proactively check processes, uncover gaps, and drive performance improvements."
        },
        {
          "key": "C",
          "text": "To issue formal findings that carry heavy compliance weight for outside parties."
        },
        {
          "key": "D",
          "text": "To assign blame to specific departments for system failures."
        }
      ],
      "correct": "B",
      "explanation": "Internal audits are self-initiated and internally managed by trained staff"
    },
    {
      "id": 3,
      "question": "When addressing a defect or failure, why is root cause analysis critical?",
      "choices": [
        {
          "key": "A",
          "text": "It allows the team to fix the immediately visible symptom quickly."
        },
        {
          "key": "B",
          "text": "It identifies who is responsible for the mistake so they can be disciplined."
        },
        {
          "key": "C",
          "text": "It uncovers the true, underlying cause so the exact same issue does not return."
        },
        {
          "key": "D",
          "text": "It helps the organization prepare frantic, last-minute documentation."
        }
      ],
      "correct": "C",
      "explanation": "Fixing only the visible symptom guarantees the problem will return"
    },
    {
      "id": 4,
      "question": "What is the fundamental difference between Corrective Action (CA) and Preventive Action (PA)?",
      "choices": [
        {
          "key": "A",
          "text": "CA fixes a problem before it occurs, while PA fixes a problem that has already happened."
        },
        {
          "key": "B",
          "text": "CA is exclusively proactive, while PA is exclusively reactive."
        },
        {
          "key": "C",
          "text": "CA addresses a problem that has already occurred, while PA addresses the risk of a problem before it occurs."
        },
        {
          "key": "D",
          "text": "CA is only used in external audits, while PA is only used in internal audits."
        }
      ],
      "correct": "C",
      "explanation": "Corrective action is reactive, aiming to eliminate the root cause of an existing nonconformity to fix the past"
    },
    {
      "id": 5,
      "question": "According to the structured framework for closing gaps effectively, what is the very first step?",
      "choices": [
        {
          "key": "A",
          "text": "Implement the Solution"
        },
        {
          "key": "B",
          "text": "Verify Effectiveness"
        },
        {
          "key": "C",
          "text": "Identify Root Cause"
        },
        {
          "key": "D",
          "text": "Define the Issue"
        }
      ],
      "correct": "D",
      "explanation": "Before you can identify a root cause or implement a solution, you must first \"Define the Issue\""
    },
    {
      "id": 6,
      "question": "In the gap-closing process, what does the step \"Verify Effectiveness\" actually require a team to do?",
      "choices": [
        {
          "key": "A",
          "text": "Confirm the implemented solution works and check that the problem has not recurred."
        },
        {
          "key": "B",
          "text": "Check if the documentation was updated immediately before the audit date."
        },
        {
          "key": "C",
          "text": "Clearly document what was found, where, and under what conditions during the initial audit."
        },
        {
          "key": "D",
          "text": "Use the 5 Whys to thoroughly trace the issue back to its source."
        }
      ],
      "correct": "A",
      "explanation": "A problem isn't genuinely solved until the conditions are fixed"
    },
    {
      "id": 7,
      "question": "Which of the following characteristics describes a state of \"Continuous Audit Readiness\" rather than \"Reactive Audit Preparation\"?",
      "choices": [
        {
          "key": "A",
          "text": "Frantic document reviews are conducted right before the audit date."
        },
        {
          "key": "B",
          "text": "Records are updated at the last minute to satisfy the auditor."
        },
        {
          "key": "C",
          "text": "Processes are documented, current, and followed daily by staff."
        },
        {
          "key": "D",
          "text": "Staff are briefed only when external auditors arrive on site."
        }
      ],
      "correct": "C",
      "explanation": "A continuous audit readiness mindset means organizations don't scramble to prepare"
    },
    {
      "id": 8,
      "question": "In the 5 Whys practice scenario where a product was delivered late, what was the actual root cause ultimately uncovered?",
      "choices": [
        {
          "key": "A",
          "text": "The logistics team delayed the shipment without reason."
        },
        {
          "key": "B",
          "text": "The final product failed the mandatory quality inspection."
        },
        {
          "key": "C",
          "text": "The inspector was not trained on the updated inspection procedure."
        },
        {
          "key": "D",
          "text": "The customer filed a formal complaint."
        }
      ],
      "correct": "C",
      "explanation": "By repeatedly asking \"why,\" the scenario traces the late delivery back to delayed inspection, which was ultimately caused by an inspector lacking training on the revised Standard Operating Procedure"
    },
    {
      "id": 9,
      "question": "Who typically conducts external audits?",
      "choices": [
        {
          "key": "A",
          "text": "Trained internal auditors working within the organization."
        },
        {
          "key": "B",
          "text": "Outside parties, such as certification bodies, regulators, or customers."
        },
        {
          "key": "C",
          "text": "Floor supervisors proactively checking daily operational tasks."
        },
        {
          "key": "D",
          "text": "The internally managed logistics and compliance team."
        }
      ],
      "correct": "B",
      "explanation": "External audits are conducted by outside parties—such as certification bodies, regulators, or customers—to independently verify that an organization meets required standards and regulatory obligations"
    },
    {
      "id": 10,
      "question": "What is the ultimate result of conducting audits focused on findings and rigorously implementing corrective actions?",
      "choices": [
        {
          "key": "A",
          "text": "Organizations learn to hide operational gaps more effectively."
        },
        {
          "key": "B",
          "text": "Every problem becomes an opportunity to build a stronger system."
        },
        {
          "key": "C",
          "text": "The need for preventive actions is completely eliminated."
        },
        {
          "key": "D",
          "text": "Audits become focused entirely on fault-finding and performance reviews."
        }
      ],
      "correct": "B",
      "explanation": "When audits focus on findings rather than fault, and CAPA rigorously closes gaps, the cycle transforms challenges into capabilities, helping organizations become more resilient, compliant, and competitive over time"
    }
  ],
  "continual-improvement": [
    {
      "id": 1,
      "question": "What is the core definition of continual improvement according to the module?",
      "choices": [
        {
          "key": "A",
          "text": "A series of dramatic, large-scale organizational overhauls."
        },
        {
          "key": "B",
          "text": "An annual project to reduce waste and eliminate errors."
        },
        {
          "key": "C",
          "text": "A disciplined habit of making small, ongoing changes to increase efficiency."
        },
        {
          "key": "D",
          "text": "A one-time methodology for managing business risks."
        }
      ],
      "correct": "C",
      "explanation": "Continual improvement is not an isolated event or massive overhaul"
    },
    {
      "id": 2,
      "question": "During which phase of the PDCA cycle should you implement a change on a small, controlled scale?",
      "choices": [
        {
          "key": "A",
          "text": "Plan"
        },
        {
          "key": "B",
          "text": "Do"
        },
        {
          "key": "C",
          "text": "Check"
        },
        {
          "key": "D",
          "text": "Act"
        }
      ],
      "correct": "B",
      "explanation": "The \"Do\" phase of the Plan-Do-Check-Act cycle involves implementing a proposed change on a small, controlled scale to test hypotheses without causing any disruption to the organization's broader live operations"
    },
    {
      "id": 3,
      "question": "Why are small improvements often preferred over large-scale, disruptive changes?",
      "choices": [
        {
          "key": "A",
          "text": "They generate less organizational resistance and are easier to test."
        },
        {
          "key": "B",
          "text": "They require a larger upfront financial investment."
        },
        {
          "key": "C",
          "text": "They rely purely on assumption rather than data."
        },
        {
          "key": "D",
          "text": "They only need to be done once to be effective."
        }
      ],
      "correct": "A",
      "explanation": "Small incremental improvements are easier to test and generate far less organizational resistance than massive overhauls"
    },
    {
      "id": 4,
      "question": "What is the primary purpose of a Management Review?",
      "choices": [
        {
          "key": "A",
          "text": "To punish employees for nonconformities."
        },
        {
          "key": "B",
          "text": "To provide leaders with a fact-based opportunity to evaluate system performance."
        },
        {
          "key": "C",
          "text": "To rely on assumptions when planning the next budget."
        },
        {
          "key": "D",
          "text": "To eliminate the need for customer feedback."
        }
      ],
      "correct": "B",
      "explanation": "Management review is a structured process giving leaders a regular, fact-based opportunity to evaluate performance"
    },
    {
      "id": 5,
      "question": "How does quality directly improve a company's profit margin?",
      "choices": [
        {
          "key": "A",
          "text": "By treating quality management as a traditional cost center."
        },
        {
          "key": "B",
          "text": "By increasing the number of warranty claims."
        },
        {
          "key": "C",
          "text": "By reducing errors, minimizing rework, and increasing customer retention."
        },
        {
          "key": "D",
          "text": "By avoiding the tracking of efficiency gains."
        }
      ],
      "correct": "C",
      "explanation": "Quality improves margins by minimizing errors and rework, which shrinks the cost of poor quality"
    },
    {
      "id": 6,
      "question": "At which system maturity level is continuous improvement fully embedded in daily operations?",
      "choices": [
        {
          "key": "A",
          "text": "Level 1 — Reactive"
        },
        {
          "key": "B",
          "text": "Level 2 — Defined"
        },
        {
          "key": "C",
          "text": "Level 3 — Controlled"
        },
        {
          "key": "D",
          "text": "Level 4 — Optimized"
        }
      ],
      "correct": "D",
      "explanation": "At Level 4, known as the Optimized stage, continuous improvement is deeply embedded within daily operations"
    },
    {
      "id": 7,
      "question": "What characterizes a \"Level 1 — Reactive\" system?",
      "choices": [
        {
          "key": "A",
          "text": "Processes are documented and consistently followed."
        },
        {
          "key": "B",
          "text": "Problems are addressed only after they occur with no prevention in place."
        },
        {
          "key": "C",
          "text": "Performance is actively measured and stable."
        },
        {
          "key": "D",
          "text": "The system proactively evolves and gets better over time."
        }
      ],
      "correct": "B",
      "explanation": "A Level 1 Reactive system completely lacks any structured internal processes or preventive measures"
    },
    {
      "id": 8,
      "question": "Which element is considered the \"multiplier for every tool and process\" when building an improvement culture?",
      "choices": [
        {
          "key": "A",
          "text": "Advanced software systems"
        },
        {
          "key": "B",
          "text": "Strict disciplinary protocols"
        },
        {
          "key": "C",
          "text": "Culture and psychological safety"
        },
        {
          "key": "D",
          "text": "Frequent leadership changes"
        }
      ],
      "correct": "C",
      "explanation": "Tools and processes alone cannot drive progress; people do"
    },
    {
      "id": 9,
      "question": "How does the module view long-term sustainability through QHSE and ESG integration?",
      "choices": [
        {
          "key": "A",
          "text": "As an unavoidable financial burden."
        },
        {
          "key": "B",
          "text": "As a strategic advantage that balances today's performance with tomorrow's impact."
        },
        {
          "key": "C",
          "text": "As a constraint that limits business growth."
        },
        {
          "key": "D",
          "text": "As a temporary initiative for public relations."
        }
      ],
      "correct": "B",
      "explanation": "Integrating QHSE with ESG principles proves that sustainability is a strategic advantage, not a constraint"
    },
    {
      "id": 10,
      "question": "What happens when the elements of system thinking work together as a unified system?",
      "choices": [
        {
          "key": "A",
          "text": "Improvement stalls due to over-complication."
        },
        {
          "key": "B",
          "text": "The system relies entirely on reactive problem solving."
        },
        {
          "key": "C",
          "text": "The results are transformational, turning effort into scalable business growth."
        },
        {
          "key": "D",
          "text": "The organization reverts to isolated disciplines."
        }
      ],
      "correct": "C",
      "explanation": "System thinking combines process design, risk management, measurement, engagement, and improvement"
    }
  ]
};
